### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by RoyEastmen** [Faithful-Resource-Pack/Faithful-Bedrock-32x#7]
So, I'm not sure why, but in Minecraft Bedrock version: 1.19.81.01 is crashing when using this texture pack on any world, server, or as a global texture pack. A lot of people have been having this problem with other packs, but some packs don't do this. It would be nice if you could find a way to fix this problem, and please feel free to contact me at any time.

**Comment by Pomi108** [comment]
This pack literally only changes textures. It's impossible for it to crash the game directly. This is most likely a quirk of Bedrock. This report is also super vague and not really helpful in finding solutions. Either way, this isn't fixable by us.
